### ISSUE TITLE
Minimesos bundles docker client in the image.

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#205] opened 2016-01-27 12:54 UTC
https://github.com/ContainerSolutions/minimesos-docker/blob/master/base/Dockerfile

Can't use minimesos cause my docker is of different version.
I can upgrade, but, it sure confuses me a lot as to why not bind it with volumes?

**Comment by frankscholten** [comment] 2016-04-13 08:38
Duplicate of https://github.com/ContainerSolutions/minimesos/issues/324

**Closed by frankscholten** 2016-04-13 08:38 UTC
Labels: versioning
