### ISSUE TITLE
duplication when it comes to the MarathonClient

### ISSUE THREAD

**Issue by sadovnikov** [ContainerSolutions/minimesos#184] opened 2015-12-10 13:46 UTC
When we are in “destroy” and “install” commands, we don’t really have a proper `MesosCluster`. 
We are not able to restore `AbstractContainer` objects from actually running cluster….  we’d need `MesosCluster(String clusterId)` constructor, which loops through running docker containers and restores objects to represent them. And then get rid of static methods in `MesosCluster`

**Comment by frankscholten** [comment] 2015-12-10 14:03
+1

**Comment by frankscholten** [comment] 2016-02-08 15:27
Duplicate of https://github.com/ContainerSolutions/minimesos/issues/213

**Closed by frankscholten** 2016-02-08 15:27 UTC
Labels: refactoring
