### ISSUE TITLE
Mesos master commits suicide 

### ISSUE THREAD

**Issue by lguminski** [ContainerSolutions/minimesos#179] opened 2015-12-07 13:12 UTC
Mesos master suddenly died after several hours. This is one host setup as this is minimesos, which makes it strange. Reporting so that you know.
```
I1207 11:13:03.269251     8 hierarchical.hpp:1326] No resources available to allocate!
I1207 11:13:03.269279     8 hierarchical.hpp:1421] No inverse offers to send out!
I1207 11:13:03.269336     8 hierarchical.hpp:1239] Performed allocation for slave 73b194ec-fd6e-48d9-9291-1cbf9271d6ea-S0 in 1.155297ms
I1207 11:13:03.661677     6 hierarchical.hpp:1521] Filtered offer with ports(*):[33000-34000]; cpus(*):4; mem(*):833; disk(*):34059 on slave 73b194ec-fd6e-48d9-9291-1cbf9271d6ea-S0 for framework 73b194ec-fd6e-48d9-9291-1cbf9271d6ea-0000
I1207 11:13:03.661993     6 hierarchical.hpp:1326] No resources available to allocate!
I1207 11:13:03.662021     6 hierarchical.hpp:1421] No inverse offers to send out!
I1207 11:13:03.662036     6 hierarchical.hpp:1221] Performed allocation for 1 slaves in 481570ns
2015-12-07 11:13:03,953:1(0x7f305a81f700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 45152097ms
2015-12-07 11:13:03,953:1(0x7f305a81f700):ZOO_INFO@check_events@1703: initiated connection to server [172.17.0.3:2181]
2015-12-07 11:13:03,953:1(0x7f305a01e700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 45152097ms
2015-12-07 11:13:03,953:1(0x7f305a01e700):ZOO_INFO@check_events@1703: initiated connection to server [172.17.0.3:2181]
2015-12-07 11:13:03,956:1(0x7f305a81f700):ZOO_ERROR@handle_socket_error_msg@1739: Socket [172.17.0.3:2181] zk retcode=-112, errno=116(Stale file handle): sessionId=0x1517940d8390001 has expired.
I1207 11:13:03.956370    13 group.cpp:490] ZooKeeper session expired
2015-12-07 11:13:03,957:1(0x7f305a01e700):ZOO_ERROR@handle_socket_error_msg@1739: Socket [172.17.0.3:2181] zk retcode=-112, errno=116(Stale file handle): sessionId=0x1517940d8390000 has expired.
I1207 11:13:03.962072     7 group.cpp:490] ZooKeeper session expired
I1207 11:13:03.962400    11 detector.cpp:144] The current leader (id=0) is lost
I1207 11:13:03.962435    11 detector.cpp:156] Detected a new leader: None
I1207 11:13:03.962654    11 master.cpp:1603] The newly elected leader is None
Lost leadership... committing suicide!
```

**Comment by frankscholten** [comment] 2016-02-28 18:44
@lguminski Did you close the lid on your Mac at some point? Wondering if it has to do with hibernation.

**Comment by frankscholten** [comment] 2016-03-14 15:36
@sadovnikov @remmelt Have you encountered this one?

**Comment by sadovnikov** [comment] 2016-03-15 09:27
from @philwinder 

I've seen this a few times. It occurs when my mac goes to sleep and wakes up. The issue is that the zookeeper counter keeps ticking away and when it wakes up it looks like the master hasn't responded for minutes/hours. I consider this expected behaviour, but thought I'd post it here anyway:

```
2016-03-15 08:07:50,876:1(0x7fad6e21c700):ZOO_WARN@zookeeper_interest@1557: Exceeded deadline by 54001067ms
2016-03-15 08:07:50,877:1(0x7fad6e21c700):ZOO_INFO@check_events@1703: initiated connection to server [172.17.0.3:2181]
2016-03-15 08:07:50,881:1(0x7fad6e21c700):ZOO_ERROR@handle_socket_error_msg@1739: Socket [172.17.0.3:2181] zk retcode=-112, errno=116(Stale file handle): sessionId=0x1537590fa2d0001 has expired.
I0315 08:07:50.882025    14 group.cpp:490] ZooKeeper session expired
I0315 08:07:50.882136     8 detector.cpp:144] The current leader (id=0) is lost
I0315 08:07:50.882202     8 detector.cpp:156] Detected a new leader: None
I0315 08:07:50.882277     8 master.cpp:1603] The newly elected leader is None
Lost leadership... committing suicide!
```

**Comment by sadovnikov** [comment] 2016-04-22 08:48
possibly related to this (from @philwinder):

I've found another "minimesos in-use" issue caused this time by zookeeper. By default, zookeeper creates a volume for its `/tmp/zookeeper`. This seems to contain some state. When restarting, it sometimes, but quite often, reuses that folder. It seems to happen when you are rapidly stopping and restarting. Then you get lots of:
```
2016-04-22 08:25:41,102 [myid:] - INFO  [NIOServerCxn.Factory:0.0.0.0/0.0.0.0:2181:ZooKeeperServer@841] - Refusing session request for client /192.168.99.1:64196 as it has seen zxid 0x1c6 our last zxid is 0x2 client must try another server
```
And everything stops working. The master crashes, applications don't start, etc. The work around is to completely wipe the volumes out every time you restart. I use this:
```
docker kill $(docker ps -a -q) ; docker rm $(docker ps --no-trunc -aq) ; docker volume rm $(docker volume ls -q)
```

**Comment by frankscholten** [comment] 2016-05-02 15:21
Closing for now as this does not seem to be something we can fix

**Closed by frankscholten** 2016-05-02 15:21 UTC
Labels: bug
