### ISSUE TITLE
kafka-mesos deployment not working

### ISSUE THREAD

**Issue by batwicket** [ContainerSolutions/minimesos#188] opened 2016-01-06 21:02 UTC
I'm trying to get kafka-mesos running, but so far it is resisting my efforts. I don't know if I'm running into issues specific to minimesos at this point. I've opened a question in stackoverflow but can move the discussion here if it's considered helpful to other devs.

http://stackoverflow.com/questions/34642188/how-can-i-launch-the-kafka-scheduler-using-marathon-in-minimesos

**Comment by batwicket** [comment] 2016-01-07 05:39
As described in the stackoverflow, a look at the docker log for the marathon container shows that the `"hostname" "LIKE" "master" line in the kafka-mesos json file is the problem. The cmd is assuming that master resolves to the IP address of the mesos master node. The mapping is done explicitly when the scheduler is launched directly with docker cli, but the context isn't present in the HTTP POST environment. I suspect they are making an assumption which does not hold in the minimesos environment. Maybe i'm not configuring something correctly..

**Comment by frankscholten** [comment] 2016-01-07 10:09
@batwicket Thanks for trying this out! Can you give some more details like which version of minimesos you are using. I think you are right about the hostname mapping. Could you run it without that mapping?

**Comment by batwicket** [comment] 2016-01-07 15:29
Yes, I'm using version 0.5.0 . I updated the stackoverflow question with some additional information since there are quite a few details. Currently i'm trying to get at the logs for the sandbox used to run the kafka scheduler but i can't do it through the mesos web gui. It thinks this is the problem: `The slave's hostname, '449cf43a4ad8', is not accessible from your network
The slave's port, '5051', is not accessible from your network
The slave timed out or went offline`

**Comment by batwicket** [comment] 2016-01-07 17:24
back. The stdout/stderr container logs show that the kafka executor is unable to connect to the zookeeper server. The cmd i'm passing is `./kafka-mesos.sh scheduler --master=192.168.99.100:5050 --zk=192.168.99.100:2181 --api=http://192.168.99.100:7000 --storage=zk:/kafka-mesos`, where the IP is returned via `docker-machine ip default`.

**Comment by batwicket** [comment] 2016-01-07 21:06
the kafka scheduler is running on playa mesos. I had to remove the constraint line and replace the 'model' in the cmd with the mesos-master ip address. No luck with minimesos so far, though. I think the sandbox running the scheduler has difficulty seeing the zookeeper node.

**Comment by batwicket** [comment] 2016-01-08 05:40
I think the LIBPROCESS_IP has to be set on the docker command line used to launch the marathon container. I'm not sure where this is configured, though. Any ideas?

**Comment by batwicket** [comment] 2016-01-08 16:22
Just heard back from Joe Stein - the settings in the kafka-mesos JSON file are aimed at a particular use case. The "master" parameter should be replaced with the IP of the master and the constraint was just intended as an example. That's consistent with what i've done already to get to this point.

**Comment by batwicket** [comment] 2016-01-09 04:18
Working.. it wants an "env" setting in the JSON:

{
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "BRIDGE",
      "image": "batwicket/kafka-mesos:0.9.2.0",
      "forcePullImage": true
    }
  },
  "id":"kafka-mesos-scheduler",
  "cpus": 0.5,
  "mem": 256,
  "ports": [7000],
  "cmd": "./kafka-mesos.sh scheduler --master=192.168.99.100:5050 --zk=192.168.99.100:2181 --api=http://192.168.99.100:7000 --storage=zk:/kafka-mesos",
  "env": {
    "LIBPROCESS_IP": "172.17.0.5"
  },
  "instances": 1
}

where "172.17.0.5" is the IP reported if you:
`docker exec -it <mesos-slave>`
then do an ifconfig.

**Comment by frankscholten** [comment] 2016-01-09 07:15
@batwicket I got an e-mail notification that you got it working but I don't see your comment anymore.

**Comment by batwicket** [comment] 2016-01-09 07:36
Yes.. it got to RUNNING status in mesos for a few minutes then timed out due to an inability to bind to the LIBPROCESS_IP IP address. I think it's just a case of getting the variable into the environment of the container which hosts the executor. An "env" setting in the JSON file didn't seem to do it.

**Comment by jackass0528** [comment] 2016-01-09 09:53
Hi guys! I'm taxi driver in Philippines and I think your talking to me in
github. I'm so sorry for late reply!

I'm the owner <jackass0528.github.com>my repository<@cebufooddroid>

By the way, if I'm not wrong, you guys helping me here. I'm right?
"actually, it's not so easy to catch-up on this tagging situation guys. I'm
sorry! (=

Thanks you guys!

I'm hoping your reply..... Have good day!

**Comment by batwicket** [comment] 2016-01-09 17:45
well.. the project is Open Source, which means that contributions and input from around the world are welcome. If you have taken the time to dig into the source and can share a solution then that's constructive and the project moves forward. Otherwise it's noise, and there is no shortage of that.

**Comment by batwicket** [comment] 2016-01-09 18:37
in hindsight that might seem a bit harsh, but I think you see my point. If you can take complex problems and reduce them to simple solutions then you are saving the time of many people and your skills have significant value. In this particular case, avoiding the need for a LIBPROCESS_IP optiion would have saved time/money. That's not meant as a criticism.. schedule issues intrude into every project. Just an observation.

**Comment by frankscholten** [comment] 2016-01-10 01:36
@batwicket I tried installing the Mesos Kafka jar without using Docker containers. This failed because the jar was not available in the slave's sandbox. See https://github.com/mesos/kafka/issues/172 with steps to reproduce.

It's unfortunate that we have to specify LIBPROCESS_IP when running in Docker mode. 

A related idea I had is to create a minimesos Docker network. That way when launching a container one can pass in a --net=minimesos flag so it can talk to minimesos. Currently the docker-java people are working on [Docker network support](https://github.com/docker-java/docker-java/pull/417).

But perhaps there are better ways to handle this issue. 

@sadovnikov @alex-glv @philwinder Any thoughts?

**Comment by batwicket** [comment] 2016-01-10 04:13
I don't know if this helps, but perhaps environment variables could be passed on the minimesos command line (they might be specific to slave/master/marathon/zookeeper docker launches)  or in a configuration file. I think some of those variables are set in MesosContainer.java: getSharedEnvVars().

**Comment by jackass0528** [comment] 2016-01-10 04:48
Ok Thanks you for reapplying!.. I'm newbe in github and I'm only a cab
driver , love to dig in this of course or furom site or what ever... :)

I'm so sorry for waiting sir!thanks for trying also. I hope you all give me
concederation that I'm so noise on your site.

Again, thank you so much to know this things, I mean forgiving me ideas for
everything if what is professional coder all about. Thanks! (=

<em>cebutaxidriver</em>
I LOVE GITHUB!

**Comment by batwicket** [comment] 2016-01-10 05:09
ok, j.. I'm not sure why you're interested in this particular issue but hopefully it helps.

**Comment by jackass0528** [comment] 2016-01-14 10:08
Hi ContainerSolutions/m,

I'd like to add you to my professional network on LinkedIn.

- ronald

Confirm that you know ronald: https://www.linkedin.com/e/v2?e=0-ije3frx8-tu&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=5F_iOsGC&invitationId=6093342663057174528








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ije3frx8-tu&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHI8uQFU_v5sgAAAVI_m8gHoKr1MJ20b_p6WCO7JJe4nBTYryJ-77miaSIVRWKnNNqJ-Q6bP4vjeupiZMai30mz3CsBYkq3OaL18BmC1yqlCOl0bIOBJWzN5zRF62PN6iwDB0wgjrayMNjjdo3osPVsSzZXW9liQV4aMB6vfYsnFw9dqx0jRhHFVL9K0EgcAW1U&eid=0-ije3frx8-tu


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ije3frx8-tu&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jackass0528** [comment] 2016-01-14 10:08
Hi ContainerSolutions/m,

I'd like to add you to my professional network on LinkedIn.

- ronald

Confirm that you know ronald: https://www.linkedin.com/e/v2?e=0-ije3fs81-9f&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=kVOkxQfb&invitationId=6093342662805508096








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ije3fs81-9f&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQFfNAvfsSL-LQAAAVI_m-DXDtAzrPcE6bLwef4WOBN4uiMqpIGQ0ejeZJKw43cq7J4EiookMNBsIZd0sCRiKv46QglCHYSYzeTWDLCJcQ8XXPAFLCkXTNO_Rg5qgoTagUA1In3oeXek_qDTgEXkIx3RBY9fVWY7CuK7Ul_-H-vDBLSTO_xX1jZl2T2nzVzuzHIP&eid=0-ije3fs81-9f


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ije3fs81-9f&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jackass0528** [comment] 2016-01-21 06:00
ronald comaling would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=9hvfs1-ijnkvr74-iu&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=kVOkxQfb&invitationID=6093342662805508096

View ronald comaling&#39;s profile: https://www.linkedin.com/e/v2?e=9hvfs1-ijnkvr74-iu&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=kVOkxQfb&invitationID=6093342662805508096





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=9hvfs1-ijnkvr74-iu&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=9hvfs1-ijnkvr74-iu&loid=AQHi1mSitJCXAAAAAVJixSVSgTkiM1XV43ferDqxFcG0nlDkSwvw9vhBmdvlfH57pa-_OGkOm-STHVMlYyXNtv08tGzuYRGewdaEeS5333puiLAZxXRb9qSPgPMi2WGpQXlLIte2bX0AkTt5jL-KiqFEiBJ6sKdzumt1s5I7t_Hwvm0598Uzany_C7d_Fkw9GUYO

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=9hvfs1-ijnkvr74-iu&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jackass0528** [comment] 2016-01-21 06:00
ronald comaling would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=faypmf-ijnkush2-l3&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=5F_iOsGC&invitationID=6093342663057174528

View ronald comaling&#39;s profile: https://www.linkedin.com/e/v2?e=faypmf-ijnkush2-l3&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=5F_iOsGC&invitationID=6093342663057174528





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=faypmf-ijnkush2-l3&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=faypmf-ijnkush2-l3&loid=AQHNaO2HQ-of_wAAAVJixW_1SDzEXWMLD-EpFkyzXYAMxl29yrxpIPqOH199r8amj6UhgbYahIPJoA8oNTILs2tCi7fiAisWSCFIAS-hixn0GwkKE2Jyf8psH6-sWhY4NX73Ojok91jZOH0eO22Eg3rJuLpBt6xCT0Kh7mBysmO6yXLT76CaFEw4v-M8VvIWY18J

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=faypmf-ijnkush2-l3&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by jackass0528** [comment] 2016-01-28 06:00
ronald comaling would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=9hvfs1-ijxkyxf9-ou&a=preRegInvite&ek=second_guest_reminder_01&li=13&m=hero&ts=accept_text&sharedKey=kVOkxQfb&invitationID=6093342662805508096

View ronald comaling&#39;s profile: https://www.linkedin.com/e/v2?e=9hvfs1-ijxkyxf9-ou&a=preRegInvite&ek=second_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=kVOkxQfb&invitationID=6093342662805508096





You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=9hvfs1-ijxkyxf9-ou&t=lun&midToken=AQFmrFVhGEd36Q&ek=second_guest_reminder_01&li=15&m=unsub&ts=HTML&eid=9hvfs1-ijxkyxf9-ou&loid=AQHDWhLUzKZQgwAAAVKG0WZ_ICqrhZ9h62CUKajTE1pvvHKUDwvjXs2kh-N2xysVh4PnhSHEUUJhFpVSh73L5TLCrJhmInQ2_eUx7svwpj1ogxXvHyFmWUwa7nWx9r36jCxetxbJKOnbI--FGcQoDTVwslfXCUe8dQbQte_yt7pwcR33yPGDrjNY8JfW8XbeO7Wi

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=9hvfs1-ijxkyxf9-ou&a=customerServiceUrl&ek=second_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by frankscholten** [comment] 2016-02-28 18:37
I installed Mesos Kafka via a quickstart script. See this PR on Mesos Kafka: https://github.com/mesos/kafka/pull/183

**Comment by frankscholten** [comment] 2016-02-28 21:34
Deploying Mesos Kafka via the Dockerfile currently fails on service discovery of Zookeeper. 

```
Exception in thread "main" org.I0Itec.zkclient.exception.ZkException: Unable to connect to minimesos-zookeeper:2181
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:66)
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:876)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:84)
	at ly.stealth.mesos.kafka.Cluster$ZkStorage.zkClient(Cluster.scala:132)
	at ly.stealth.mesos.kafka.Cluster$ZkStorage.loadJson(Cluster.scala:147)
	at ly.stealth.mesos.kafka.Cluster$Storage.load(Cluster.scala:95)
	at ly.stealth.mesos.kafka.Cluster.load(Cluster.scala:53)
	at ly.stealth.mesos.kafka.Scheduler$.start(Scheduler.scala:373)
	at ly.stealth.mesos.kafka.Cli$SchedulerCli$.handle(Cli.scala:369)
	at ly.stealth.mesos.kafka.Cli$.exec(Cli.scala:54)
	at ly.stealth.mesos.kafka.Cli$.main(Cli.scala:36)
	at ly.stealth.mesos.kafka.Cli.main(Cli.scala)
Caused by: java.net.UnknownHostException: minimesos-zookeeper: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:922)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1316)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1269)
	at java.net.InetAddress.getAllByName(InetAddress.java:1185)
	at java.net.InetAddress.getAllByName(InetAddress.java:1119)
	at org.apache.zookeeper.ClientCnxn.<init>(ClientCnxn.java:387)
	at org.apache.zookeeper.ClientCnxn.<init>(ClientCnxn.java:332)
	at org.apache.zookeeper.ZooKeeper.<init>(ZooKeeper.java:383)
	at org.I0Itec.zkclient.ZkConnection.connect(ZkConnection.java:64)
	... 12 more
```

Currently we support using MESOS_MASTER_IP_TOKEN as a placeholder in the Marathon JSON file but we should also support MESOS_ZOOKEEPER_IP_TOKEN.

Ultimately a better solution would be to automatically register container IP addresses with a mDNS system like Avahi.

I will two issues to track this work

**Comment by frankscholten** [comment] 2016-03-16 10:20
Fixed in https://github.com/mesos/kafka/pull/183

**Closed by frankscholten** 2016-03-16 10:20 UTC
Labels: frameworks
