### ISSUE TITLE
Minimesos doesn't run from docker container

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#175] opened 2015-11-27 13:25 UTC
Trying to spin up a cluster without installing anything but docker.
The command is:
```docker run -v /var/run/docker.sock:/var/run/docker.sock -v /usr/bin/docker:/usr/bin/docker  -v /var/lib/docker:/var/lib/docker -v /sys/fs/cgroup:/sys/fs/cgroup containersol/minimesos up```

Agent node exits immediately, while master keeps on waiting until it hits the time out:
```Failed to create a containerizer: Could not create DockerContainerizer: Failed to create docker: Failed to get docker version: Failed to execute 'docker -H unix:///var/run/docker.sock --version': exited with status 127```

I face the same issue with ```minimesos up```

Docker version:
```
 % docker --version
Docker version 1.9.1
```

Running on linux, without VMs.

**Comment by mdirkse** [comment] 2015-11-29 23:49
Is this a duplicate of #164?

**Comment by sadovnikov** [comment] 2015-12-02 08:45
It is a duplicate of #164

**Closed** 2015-12-02 08:45 UTC
