### ISSUE TITLE
Malformed Host Header when using Docker from mesos-agent

### ISSUE THREAD

**Issue by rrichardson** [ContainerSolutions/minimesos#396] opened 2016-04-14 21:18 UTC
This might be related to : https://github.com/docker/docker/issues/20865 

Not sure.  

Is there a tag of a mesos-agent I could use that would have the latest docker?

**Comment by rrichardson** [comment] 2016-04-14 21:53
I updated https://github.com/ContainerSolutions/minimesos-docker/blob/master/base/Dockerfile to point to docker 1.10.1 to match my host's docker version and it now deploys correctly.

**Comment by frankscholten** [comment] 2016-04-15 08:36
@rrichardson Thanks for reporting this. 

@alex-glv Would resolving https://github.com/ContainerSolutions/minimesos/issues/324 solve this problem?

**Comment by pdxjohnny** [comment] 2016-05-26 07:42
This is definitely the same issue as the docker issue you mentioned, something to do with go 1.6

Here's what I got after

```bash
minimesos init
minimesos up
```

```log
Failed to launch container: Failed to 'docker -H unix:///var/run/docker.sock pull weaveworks/scope:0.13.1': exit status = exited with status 1 stderr = Error response from daemon: 400 Bad Request: malformed Host header
```

**Comment by frankscholten** [comment] 2016-05-26 08:18
@pdxjohnny What is your environment? Linux, Docker, Golang version et cetera?

**Comment by pdxjohnny** [comment] 2016-05-26 09:00
```log
$ uname -a
Linux john-laptop 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux

$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Mon May  2 00:06:51 2016
 OS/Arch:      linux/amd64

$ go version
go version go1.6.2 linux/amd64

$ docker images
REPOSITORY                       TAG                        IMAGE ID            CREATED             SIZE
alpine                           edge                       29cc5addcb99        2 weeks ago         4.799 MB
alpine                           latest                     13e1761bf172        2 weeks ago         4.793 MB
containersol/minimesos           0.9.0                      038eacca50ab        3 weeks ago         130.5 MB
containersol/consul-server       0.6-1                      3e27f63d1da2        3 weeks ago         37.75 MB
alpine                           3.3                        d7a513a663c1        7 weeks ago         4.794 MB
alpine                           3.1                        d1ddf5beba42        7 weeks ago         5.04 MB
gcc                              latest                     620d49f54058        9 weeks ago         1.392 GB
containersol/mesos-agent         0.25.0-0.2.70.ubuntu1404   a9221d758cf8        9 weeks ago         468.1 MB
containersol/mesos-master        0.25.0-0.2.70.ubuntu1404   43eef26e2664        9 weeks ago         468.1 MB
sdb_service                      latest                     9738ff72b595        9 weeks ago         13.32 MB
debian                           sid                        2c26136de11b        10 weeks ago        119 MB
mysql                            latest                     7a5866c2edbf        10 weeks ago        361.2 MB
weaveworks/scope                 0.13.1                     d721bbaaca35        11 weeks ago        83.86 MB
ubuntu                           latest                     e17b56e5200a        12 weeks ago        187.9 MB
mesosphere/marathon              v0.15.3                    cb206b7716b0        3 months ago        818.3 MB
jplock/zookeeper                 3.4.6                      66b763a96616        3 months ago        163.2 MB
mongo                            latest                     a5d16d62f4cf        3 months ago        317.4 MB
debian                           8                          9a02f494bef8        4 months ago        125.1 MB
gliderlabs/registrator           v6                         52cf0f3bb1e9        9 months ago        20.93 MB
docker/whalesay                  latest                     6b362a9f73eb        12 months ago       247 MB
```

Minimesos gives no version but i just installed it a about and hour ago. I get that error for any container I try to run in Marathon. Let me know if that helps sorry I don't know what possessed me to comment and give no information :stuck_out_tongue:

**Comment by frankscholten** [comment] 2016-07-06 13:16
Can't seem to reproduce this one. I switched to go 1.6.2 using GVM: https://github.com/moovweb/gvm

```
frank@franktop:~$ uname -a
Linux franktop 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
frank@franktop:~$ docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 22:00:43 2016
 OS/Arch:      linux/amd64
```
```
frank@franktop:~$ go version
go version go1.6.2 linux/amd64
```
```
frank@franktop:~$ docker images | grep containersol
containersol/mesos-hello-world-scheduler   latest                      ffc5e80b7a20        51 minutes ago      575.5 MB
containersol/mesos-hello-world-executor    latest                      fce8df5032a4        51 minutes ago      572.6 MB
containersol/minimesos-cli                 latest                      a034148e2fbb        54 minutes ago      130.6 MB
containersol/mesos-master                  0.28.1-2.0.20.ubuntu1404    bad81c56e313        About an hour ago   582.4 MB
containersol/mesos-agent                   0.28.1-2.0.20.ubuntu1404    e87913e8a02a        About an hour ago   582.4 MB
containersol/mesos-agent                   0.28.0-2.0.16.ubuntu1404    41505167bf84        About an hour ago   582.2 MB
containersol/mesos-master                  0.28.0-2.0.16.ubuntu1404    13f38a10531f        About an hour ago   582.2 MB
containersol/mesos-agent                   0.27.1-2.0.226.ubuntu1404   157127335373        About an hour ago   580 MB
containersol/mesos-master                  0.27.1-2.0.226.ubuntu1404   c8101c99cd2b        About an hour ago   580 MB
containersol/mesos-agent                   0.27.0-0.2.190.ubuntu1404   464895e42e5b        About an hour ago   579.9 MB
containersol/mesos-master                  0.27.0-0.2.190.ubuntu1404   a00f7ccd299a        About an hour ago   579.9 MB
containersol/mesos-master                  0.26.0-0.2.145.ubuntu1404   4623a328ae1b        About an hour ago   573.8 MB
containersol/mesos-agent                   0.26.0-0.2.145.ubuntu1404   d693069dc3e1        About an hour ago   573.8 MB
containersol/mesos-master                  0.25.0-0.2.70.ubuntu1404    ac5a6d9c33c9        About an hour ago   569.6 MB
containersol/mesos-agent                   0.25.0-0.2.70.ubuntu1404    b4f7aca2151f        About an hour ago   569.6 MB
containersol/mesos-base                    0.1.0                       0933285e20f5        About an hour ago   372.1 MB
containersol/alpine3.3-java8-jre           v1                          1f3497fa9280        About an hour ago   109.1 MB
containersol/minimesos                     0.9.0                       038eacca50ab        8 weeks ago         130.6 MB
containersol/minimesos                     latest                      038eacca50ab        8 weeks ago         130.6 MB
containersol/consul-server                 0.6-1                       3e27f63d1da2        9 weeks ago         37.77 MB
containersol/consul-server                 0.6                         c436b1e01e87        3 months ago        37.77 MB
```
```
frank@franktop:~$ minimesos up
Minimesos cluster is running: 3183835467
Mesos version: 0.25
export MINIMESOS_NETWORK_GATEWAY=172.17.0.1
export MINIMESOS_AGENT=http://172.17.0.5:5051; export MINIMESOS_AGENT_IP=172.17.0.5
export MINIMESOS_ZOOKEEPER=zk://172.17.0.3:2181/mesos; export MINIMESOS_ZOOKEEPER_IP=172.17.0.3
export MINIMESOS_MARATHON=http://172.17.0.6:8080; export MINIMESOS_MARATHON_IP=172.17.0.6
export MINIMESOS_CONSUL=http://172.17.0.7:8500; export MINIMESOS_CONSUL_IP=172.17.0.7
export MINIMESOS_MASTER=http://172.17.0.4:5050; export MINIMESOS_MASTER_IP=172.17.0.4
```

**Comment by frankscholten** [comment] 2016-08-08 21:28
@pdxjohnny Can you check with the latest minimesos version: 0.10.2 to see if that error still occurs?

**Comment by frankscholten** [comment] 2016-11-06 15:10
Closing as I can't reproduce this one. @pdxjohnny @rrichardson let me know if this still is a problem.

**Closed by frankscholten** 2016-11-06 15:10 UTC
Labels: bug
