### ISSUE TITLE
`minimesos info` does not test whether the cluster is actually running

### ISSUE THREAD

**Issue by jhftrifork** [ContainerSolutions/minimesos#145] opened 2015-11-04 09:49 UTC
## Steps to reproduce

1. `minimesos up`
2. `docker ps` and kill all relevant containers
3. `minimesos info`

## Expected behavior

```
> minimesos info
Minimesos cluster is not running
```

## Actual behavior

```
> ./bin/minimesos info
Minimesos cluster is running
Mesos version: 0.25.0
```

**Comment by jrslv** [comment] 2015-11-04 09:59
This is actually taken care of in #139, that is not merged yet. The issue is #139 only checks presence of `master`, so I will extend it to be more robust. However I think this issue is not valid anymore, considering the other PR. Agree?

**Closed** 2015-11-04 13:38 UTC
