### ISSUE TITLE
Service discovery and networking

### ISSUE THREAD

**Issue by alex-glv** [ContainerSolutions/minimesos#306] opened 2016-03-16 14:38 UTC
This is an umbrella issue for service discovery and networking related problems.

Current milestone is "0.8.0 - Consul based service discovery" - why is it consul based? Are we considering alternative solutions, weaveDNS or mesos-dns?

Current discussion is centered around registering mesos tasks. What if register frameworks instead and attach a load-balancer / proxy on a framework level, and not task?

**Comment by frankscholten** [comment] 2016-03-16 17:08
Duplicate of https://github.com/ContainerSolutions/minimesos/issues/263

`master` contains Consul + Registrator and we are looking at Weave. 

Let me change the milestone.

**Closed by frankscholten** 2016-03-16 17:08 UTC
Labels: servicediscovery
