### ISSUE TITLE
No error message when cluster no longer present

### ISSUE THREAD

**Issue by remmelt** [ContainerSolutions/minimesos#104] opened 2015-10-15 22:13 UTC
Use docker machine with the boot2docker image.

Run `minimesos up`

Delete the machine and create a new one:

```
docker-machine rm default
docker-machine create --driver virtualbox --virtualbox-memory 8192 default
docker-machine start default
eval $(docker-machine env default)
```

Run `minimesos up`

Nothing happens. Minimesos expects there to still be a cluster, no error messages or anything. This can be fixed by doing `minimesos destroy`.

**Comment by frankscholten** [comment] 2015-10-20 14:15
Should be fixed by https://github.com/ContainerSolutions/mini-mesos/issues/107

**Comment by frankscholten** [comment] 2015-10-21 08:30
@remmelt Can you retest on master?

**Comment by remmelt** [comment] 2015-10-21 08:50
Yes, but that'll be tomorrow when I get back from Zürich!

**Comment by sadovnikov** [comment] 2015-10-26 16:37
creating cluster in one docker-machine
```
vikmac:tmp vik$ minimesos up
Pulling containersol/minimesos:latest
.....
Status: Image is up to date for containersol/mesos-master:0.25.0-0.2.70.ubuntu1404
http://172.17.1.106:5050
vikmac:tmp vik$ docker ps
CONTAINER ID        IMAGE                                                COMMAND                CREATED             STATUS              PORTS                          NAMES
2b4539915cf8        mesosphere/marathon:v0.8.1                           "./bin/start --maste   8 seconds ago       Up 5 seconds                                       minimesos-marathon-87369170-3768931916      
133e1ef1fa32        containersol/mesos-agent:0.25.0-0.2.70.ubuntu1404    "mesos-slave"          10 seconds ago      Up 8 seconds        5051/tcp, 9200/tcp, 9300/tcp   minimesos-agent-87369170-638664633          
d0115f0dc9b6        containersol/mesos-master:0.25.0-0.2.70.ubuntu1404   "mesos-master --regi   11 seconds ago      Up 9 seconds        5050/tcp                       minimesos-master-87369170-314247353         
2e55f62921b3        jplock/zookeeper:latest                              "/opt/zookeeper/bin/   13 seconds ago      Up 10 seconds       2181/tcp, 2888/tcp, 3888/tcp   minimesos-zookeeper-87369170-580818174 
```

machine was re-created in another terminal

```
vikmac:tmp vik$ eval $(docker-machine env minimesos)
vikmac:tmp vik$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

vikmac:tmp vik$ minimesos up
Pulling containersol/minimesos:latest
.....
Digest: sha256:8e4016710be3cf3912578960b626af57c5a4fdfc5347ff9325d77f34a1c5aacd
Status: Downloaded newer image for containersol/mesos-master:0.25.0-0.2.70.ubuntu1404
vikmac:tmp vik$ docker ps 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
```

The problem is **NOT** resolved. 

* cluster ID is available
* cluster is missing

What is expected behaviour of the system?

**Comment by jrslv** [comment] 2015-11-03 08:43
#140

**Closed** 2015-11-04 13:26 UTC
Labels: bug
